### ISSUE TITLE
Rofi error and cant log out and some little issues

### ISSUE THREAD

**Issue by ShadeZE** [Axarva/dotfiles-2.0#164]
**Describe the bug**
Ok so i just installed xmonad and stuff and i am pretty new to it. I built eww on my own from the website and everything is working fine. However if try to log out, restart or shutdown from dashboard, log out menu or sidebar and error pops,
*validating the theme failed: variable border in window(border-colour:var{border})
failed to resolve*
and then i am not able to press y or n and computer doesnt log out.

Some minor issues->
weather doesnt work even after adding api key and city key.
avatar pic doesnt work too even after adding full path.
sometimes the sidebar or the dashboard glitches and doesnt get closed.

**To Reproduce**
1. Go to log out menu by win + shift + q
2. Click on 'log out/restart/shut down'
3. See error

**Expected behavior**
No error should have been popped and computer should be have logged out.

**Screenshots**
cannot take screenshot of the error.

**Desktop (please complete the following information):**
 - OS: Garuda Linux

**Additional context**

**Comment by Axarva** [comment]
This is due to your rofi version. 

The fix is to do this:

- Open the file `~/.config/rofi/powermenu/message.rasi` in a text editor.

- Remove the following lines:
`text-color:				@border;`
` border-color:           @border;`

That should fix it.

**Comment by Axarva** [comment]
The sidebar glitching is an issue in elkowar/eww, I'm surprised it hasn't been fixed yet.

Try running the script `~/.config/eww/scripts/getweather` manually and attach the logs so we can fix the weather widget.

What's the avatar pic path you're using?

**Comment by ShadeZE** [comment]
> This is due to your rofi version.
> 
> The fix is to do this:
> 
> * Open the file `~/.config/rofi/powermenu/message.rasi` in a text editor.
> * Remove the following lines:
>   `text-color:				@border;`
>   ` border-color:           @border;`
> 
> That should fix it.

that didnt fix it and text-colour was not @border but @selected.

**Comment by ShadeZE** [comment]
> The sidebar glitching is an issue in elkowar/eww, I'm surprised it hasn't been fixed yet.
> 
Ok so is there no way to fix that?
 
> Try running the script `~/.config/eww/scripts/getweather` manually and attach the logs so we can fix the weather widget.
> 
the widget worked after running it, thanks.
> What's the avatar pic path you're using?

$HOME/Downloads/picture.jpg

oh yeah and i forgot to tell that quotes are not working too.
they are in my crontab but still dont work.
i tried to click screenshot of dashboard but its blurred for some reason.
![image](https://user-images.githubusercontent.com/111891268/188296300-0b3881ff-d3c3-44cd-bb7a-24523f9b9fea.png)
And its background is not blurred like in your picture but it is totally black.

**Comment by TheBearodactyl** [comment]
> > This is due to your rofi version.
> > The fix is to do this:
> > 
> > * Open the file `~/.config/rofi/powermenu/message.rasi` in a text editor.
> > * Remove the following lines:
> >   `text-color:				@border;`
> >   ` border-color:           @border;`
> > 
> > That should fix it.
> 
> `that didnt fix it and text-colour was not @border but @selected.`

yeah, thing is, those lines DO exist in the file, they just aren't in that order, nor are they grouped together. get some brains, will you?
